project_name: croc
build:
  main: main.go
  binary: croc
  ldflags: -s -w -X main.Version="v{{.Version}}-{{.Date}}"
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
    - arm
    - arm64
  ignore:
    - goos: freebsd
      goarch: arm
  goarm:
    - 7
nfpms:
  -
    formats:
      - deb
    vendor: "schollz.com"
    homepage: "https://schollz.com/software/croc/"
    maintainer: "Zack Scholl <zack.scholl@gmail.com>"
    description: "A simple, secure, and fast way to transfer data."
    license: "MIT"
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
archives:
  -
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
    - README.md
    - LICENSE
    - zsh_autocomplete
    - bash_autocomplete
